version: '3'

services:
  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - metrics

networks:
  metrics:
    driver: bridge

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
        -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
        - 3000:3000
    networks:
        - metrics

networks:
    metrics:
        driver: bridge

  sonarqube:
    image: sonarqube:community
    privileged: true
    depends_on:
      - postgres
    environment:
      - "TZ=Europe/Lisbon"
      - "ES_JAVA_HOME=/opt/java/openjdk"
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000

  postgres:
    image: postgres:12.7
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonardb
      POSTGRES_PASSWORD: postgrespwd