name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build -t fintrackr-backend .
    - name: Run the Docker container
      run: |
        docker run -d -p 3000:3000 fintrackr-backend
